[project]
name = 'DeMiPool'
description = 'descentralized mining pool SC'
authors = []
telemetry = false
cache_dir = '.cache'

# TODO: do we need both of these for stacking?
[[project.requirements]]
contract_id = 'SP000000000000000000002Q6VF78.pox-2'

[[project.requirements]]
contract_id = 'ST000000000000000000002AMW42H.pox-2'

[contracts.stacking-pool]
path = 'contracts/stacking-pool.clar'
clarity_version = 2
epoch = 2.1

[contracts.mining-pool]
path = 'contracts/mining-pool.clar'
clarity_version = 2
epoch = 2.1

[contracts.mining-pool-5-blocks]
path = 'contracts/mining-pool-5-blocks.clar'
clarity_version = 2
epoch = 2.1

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
